#!/bin/bash
#chkconfig: 2345 87 04
#description: LISTENER daemons
#

#CALA_HOME=/usr/local/tomcat
#ORA_OWNER=oracle

case "$1" in
'start')
#su - $ORA_OWNER -c "$ORA_HOME/bin/lsnrctl start"

JAVA_HOME=/usr/java/default
CLASSPATH=$JAVA_HOME/lib
PATH=$PATH:$JAVA_HOME/bin
export PATH CLASSPATH JAVA_HOME

/usr/local/tomcat/bin/startup.sh


;;

'stop')
#su - $ORA_OWNER -c "$ORA_HOME/bin/lsnrctl stop"
JAVA_HOME=/usr/java/default
CLASSPATH=$JAVA_HOME/lib
PATH=$PATH:$JAVA_HOME/bin
export PATH CLASSPATH JAVA_HOME

/usr/local/tomcat/bin/shutdown.sh
;;

'restart')
$0 stop
$0 start
;;

esac
